### ISSUE TITLE
How can I listen to transactions?

### ISSUE THREAD

**Issue by Head** [mappum/bitcoin-net#43]
Now since I'm getting connections and figured out how to use the debug command I see a lot of pingpongs and the blocks.

Shouldn't I also get the "inv" for **all** transactions? How can I listen to (and send back raw) transactions?

**Comment by mappum** [comment]
By default, we tell our peers not to relay transactions (in order to save on bandwidth). If you are listening for specfic transactions, you can send the peers a Bloom filter and they will only relay the relevant transactions (see [`bitcoin-filter`](https://github.com/mappum/bitcoin-filter)). If you really do want all transactions, you can add this option to your `PeerGroup` constructor: `{ peerOpts: { relay: true } }`.

Once you have peers sending you these transactions, the best way to handle them is to use the [`bitcoin-inventory`](https://github.com/mappum/bitcoin-inventory) module. This will automatically fetch transactions we have not yet seen, and will help in announcing transactions that we have created.

**Comment by Head** [comment]
Wow. That works great! Add this to the docs :)

@ChangeTip, send one beer to @mappum

**Comment by changetip** [comment]
Hi @mappum, @Head sent you a tip worth one beer (5,191 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/949688)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by mappum** [comment]
Thank you 😄 🍺
